/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, copyDefault, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && (copyDefault || key !== "default"))
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toCommonJS = /* @__PURE__ */ ((cache) => {
  return (module2, temp) => {
    return cache && cache.get(module2) || (temp = __reExport(__markAsModule({}), module2, 1), cache && cache.set(module2, temp), temp);
  };
})(typeof WeakMap !== "undefined" ? /* @__PURE__ */ new WeakMap() : 0);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => main_default
});

// src/ObsidianIcalPlugin.ts
var import_obsidian4 = require("obsidian");

// src/Model/Settings.ts
var DEFAULT_SETTINGS = {
  githubPersonalAccessToken: "",
  githubGistId: "",
  githubUsername: "",
  filename: "obsidian.ics",
  isPeriodicSaveEnabled: true,
  periodicSaveInterval: 5,
  isSaveToGistEnabled: false,
  isSaveToFileEnabled: false,
  isSaveToWebEnabled: false,
  savePath: "",
  saveFileName: "",
  saveFileExtension: ".ical",
  howToParseInternalLinks: "DoNotModifyThem",
  ignoreCompletedTasks: false,
  isDebug: false,
  includeEventsOrTodos: "EventsOnly",
  isOnlyTasksWithoutDatesAreTodos: true,
  ignoreOldTasks: false,
  oldTaskInDays: 365,
  howToProcessMultipleDates: "PreferDueDate",
  isDayPlannerPluginFormatEnabled: false,
  isIncludeTasksWithTags: false,
  includeTasksWithTags: "#calendar",
  isExcludeTasksWithTags: false,
  excludeTasksWithTags: "#ignore",
  rootPath: "/",
  isIncludeLinkInDescription: false,
  secretKey: ""
};

// src/Logger.ts
var import_obsidian = require("obsidian");
var Logger = class {
  constructor(isDebug) {
    this.isDebug = isDebug;
  }
  static getInstance(isDebug) {
    if (!Logger.instance) {
      Logger.instance = new Logger(isDebug != null ? isDebug : false);
    } else if (isDebug !== void 0) {
      Logger.instance.isDebug = isDebug;
    }
    return Logger.instance;
  }
  log(message, object) {
    if (this.isDebug) {
      console.log("[" + (0, import_obsidian.moment)().format("YYYY-MM-DD-HH:mm:ss.SSS") + "][info][ical] " + message);
      if (object) {
        console.log(object);
      }
    }
  }
};
function logger(isDebug) {
  return Logger.getInstance(isDebug);
}
function log(message, object) {
  return Logger.getInstance().log(message, object);
}

// src/SettingsManager.ts
var SettingsManager = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  static async createInstance(plugin) {
    SettingsManager.instance = new SettingsManager(plugin);
    await SettingsManager.instance.loadSettings();
    return SettingsManager.instance;
  }
  static get settingsManager() {
    return SettingsManager.instance;
  }
  async loadSettings() {
    log("Load settings");
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.plugin.loadData());
    await this.plugin.saveData(this.settings);
  }
  async saveSettings() {
    log("Save settings");
    await this.plugin.saveData(this.settings);
  }
  get githubPersonalAccessToken() {
    return this.settings.githubPersonalAccessToken;
  }
  set githubPersonalAccessToken(value) {
    this.settings.githubPersonalAccessToken = value;
    this.saveSettings();
  }
  get githubGistId() {
    return this.settings.githubGistId;
  }
  set githubGistId(value) {
    this.settings.githubGistId = value;
    this.saveSettings();
  }
  get githubUsername() {
    return this.settings.githubUsername;
  }
  set githubUsername(value) {
    this.settings.githubUsername = value;
    this.saveSettings();
  }
  get filename() {
    return this.settings.filename;
  }
  set filename(value) {
    this.settings.filename = value;
    this.saveSettings();
  }
  get isPeriodicSaveEnabled() {
    return this.settings.isPeriodicSaveEnabled;
  }
  set isPeriodicSaveEnabled(value) {
    this.settings.isPeriodicSaveEnabled = value;
    this.saveSettings();
  }
  get periodicSaveInterval() {
    return this.settings.periodicSaveInterval;
  }
  set periodicSaveInterval(value) {
    this.settings.periodicSaveInterval = value;
    this.saveSettings();
  }
  get isSaveToGistEnabled() {
    return this.settings.isSaveToGistEnabled;
  }
  set isSaveToGistEnabled(value) {
    this.settings.isSaveToGistEnabled = value;
    this.saveSettings();
  }
  get isSaveToFileEnabled() {
    return this.settings.isSaveToFileEnabled;
  }
  set isSaveToFileEnabled(value) {
    this.settings.isSaveToFileEnabled = value;
    this.saveSettings();
  }
  get savePath() {
    return this.settings.savePath;
  }
  set savePath(value) {
    this.settings.savePath = value;
    this.saveSettings();
  }
  get saveFileName() {
    return this.settings.saveFileName;
  }
  set saveFileName(value) {
    this.settings.saveFileName = value;
    this.saveSettings();
  }
  get saveFileExtension() {
    return this.settings.saveFileExtension;
  }
  set saveFileExtension(value) {
    this.settings.saveFileExtension = value;
    this.saveSettings();
  }
  get howToParseInternalLinks() {
    return this.settings.howToParseInternalLinks;
  }
  set howToParseInternalLinks(value) {
    this.settings.howToParseInternalLinks = value;
    this.saveSettings();
  }
  get ignoreCompletedTasks() {
    return this.settings.ignoreCompletedTasks;
  }
  set ignoreCompletedTasks(value) {
    this.settings.ignoreCompletedTasks = value;
    this.saveSettings();
  }
  get isDebug() {
    return this.settings.isDebug;
  }
  set isDebug(value) {
    this.settings.isDebug = value;
    this.saveSettings();
  }
  get ignoreOldTasks() {
    return this.settings.ignoreOldTasks;
  }
  set ignoreOldTasks(value) {
    this.settings.ignoreOldTasks = value;
    this.saveSettings();
  }
  get oldTaskInDays() {
    return this.settings.oldTaskInDays;
  }
  set oldTaskInDays(value) {
    this.settings.oldTaskInDays = value;
    this.saveSettings();
  }
  get howToProcessMultipleDates() {
    return this.settings.howToProcessMultipleDates;
  }
  set howToProcessMultipleDates(value) {
    this.settings.howToProcessMultipleDates = value;
    this.saveSettings();
  }
  get includeEventsOrTodos() {
    return this.settings.includeEventsOrTodos;
  }
  set includeEventsOrTodos(value) {
    this.settings.includeEventsOrTodos = value;
    this.saveSettings();
  }
  get isOnlyTasksWithoutDatesAreTodos() {
    return this.settings.isOnlyTasksWithoutDatesAreTodos;
  }
  set isOnlyTasksWithoutDatesAreTodos(value) {
    this.settings.isOnlyTasksWithoutDatesAreTodos = value;
    this.saveSettings();
  }
  get isDayPlannerPluginFormatEnabled() {
    return this.settings.isDayPlannerPluginFormatEnabled;
  }
  set isDayPlannerPluginFormatEnabled(value) {
    this.settings.isDayPlannerPluginFormatEnabled = value;
    this.saveSettings();
  }
  get isIncludeTasksWithTags() {
    return this.settings.isIncludeTasksWithTags;
  }
  set isIncludeTasksWithTags(value) {
    this.settings.isIncludeTasksWithTags = value;
    this.saveSettings();
  }
  get includeTasksWithTags() {
    return this.settings.includeTasksWithTags;
  }
  set includeTasksWithTags(value) {
    this.settings.includeTasksWithTags = value;
    this.saveSettings();
  }
  get isExcludeTasksWithTags() {
    return this.settings.isExcludeTasksWithTags;
  }
  set isExcludeTasksWithTags(value) {
    this.settings.isExcludeTasksWithTags = value;
    this.saveSettings();
  }
  get excludeTasksWithTags() {
    return this.settings.excludeTasksWithTags;
  }
  set excludeTasksWithTags(value) {
    this.settings.excludeTasksWithTags = value;
    this.saveSettings();
  }
  get rootPath() {
    return this.settings.rootPath;
  }
  set rootPath(value) {
    this.settings.rootPath = value;
    this.saveSettings();
  }
  get isIncludeLinkInDescription() {
    return this.settings.isIncludeLinkInDescription;
  }
  set isIncludeLinkInDescription(value) {
    this.settings.isIncludeLinkInDescription = value;
    this.saveSettings();
  }
  get secretKey() {
    return this.settings.secretKey;
  }
  set secretKey(value) {
    this.settings.secretKey = value;
    this.saveSettings();
  }
  get isSaveToWebEnabled() {
    return this.settings.isSaveToWebEnabled;
  }
  set isSaveToWebEnabled(value) {
    this.settings.isSaveToWebEnabled = value;
    this.saveSettings();
  }
};

// src/Service/ICalBuilder.ts
var ICalBuilder = class {
  constructor() {
    this.lines = [];
    this.lines.push("BEGIN:VCALENDAR");
    this.lines.push("VERSION:2.0");
    this.lines.push("PRODID:-//liuh886//obsidian-ical-plugin-pro v2.1.0//EN");
    this.lines.push("CALSCALE:GREGORIAN");
  }
  setCalendarName(name) {
    this.lines.push(`X-WR-CALNAME:${this.escapeText(name)}`);
    this.lines.push(`NAME:${this.escapeText(name)}`);
    return this;
  }
  setTimezone(tz) {
    this.lines.push(`X-WR-TIMEZONE:${tz}`);
    return this;
  }
  setLastUpdated(date) {
    const formattedDate = date.toISOString().replace(/[-:]/g, "").split(".")[0] + "Z";
    this.lines.push(`X-WR-DATE:${formattedDate}`);
    this.lines.push(`X-WR-CALDESC:Last updated at ${date.toLocaleString()}`);
    return this;
  }
  setRefreshInterval(minutes) {
    this.lines.push(`X-PUBLISHED-TTL:PT${minutes}M`);
    this.lines.push(`REFRESH-INTERVAL;VALUE=DURATION:PT${minutes}M`);
    return this;
  }
  addProperty(key, value) {
    this.lines.push(`${key}:${this.escapeText(value)}`);
    return this;
  }
  beginEvent() {
    this.lines.push("BEGIN:VEVENT");
    return this;
  }
  endEvent() {
    this.lines.push("END:VEVENT");
    return this;
  }
  beginToDo() {
    this.lines.push("BEGIN:VTODO");
    return this;
  }
  endToDo() {
    this.lines.push("END:VTODO");
    return this;
  }
  addEventProperty(key, value, escape = true) {
    const escapedValue = escape ? this.escapeText(value) : value;
    this.lines.push(`${key}:${escapedValue}`);
    return this;
  }
  build() {
    this.lines.push("END:VCALENDAR");
    return this.lines.map((line) => this.foldLine(line)).join("\r\n") + "\r\n";
  }
  escapeText(text) {
    return text.replace(/\\/g, "\\\\").replace(/;/g, "\\;").replace(/,/g, "\\,").replace(/\n/g, "\\n").replace(/\r/g, "");
  }
  foldLine(line) {
    if (line.length <= 75)
      return line;
    let result = "";
    let currentLine = line;
    while (currentLine.length > 75) {
      result += currentLine.substring(0, 75) + "\r\n ";
      currentLine = currentLine.substring(75);
    }
    result += currentLine;
    return result;
  }
};

// src/Service/IcalService.ts
var IcalService = class {
  getCalendar(tasks, settings) {
    const builder = new ICalBuilder();
    const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
    builder.setCalendarName("Obsidian Calendar").setTimezone(timezone).setLastUpdated(new Date()).setRefreshInterval(settings.periodicSaveInterval || 15);
    const includeEvents = settings.includeEventsOrTodos === "EventsAndTodos" || settings.includeEventsOrTodos === "EventsOnly";
    const includeTodos = settings.includeEventsOrTodos === "EventsAndTodos" || settings.includeEventsOrTodos === "TodosOnly";
    if (includeEvents) {
      this.addEventsToBuilder(tasks, settings, builder);
    }
    if (includeTodos) {
      this.addToDosToBuilder(tasks, settings, builder);
    }
    return builder.build();
  }
  addEventsToBuilder(tasks, settings, builder) {
    tasks.forEach((task) => {
      this.addEventToBuilder(task, null, "", settings, builder);
    });
  }
  addEventToBuilder(task, date, prependSummary, settings, builder) {
    if (task.hasAnyDate() === false) {
      return;
    }
    if (date === null) {
      switch (settings.howToProcessMultipleDates) {
        case "PreferStartDate":
          builder.beginEvent();
          this.addEventCoreProperties(task, builder);
          if (task.hasA("Start")) {
            builder.addEventProperty("DTSTART", task.getDate("Start", "YYYYMMDD"), false);
          } else if (task.hasA("Due")) {
            builder.addEventProperty("DTSTART", task.getDate("Due", "YYYYMMDD"), false);
          } else if (task.hasA("TimeStart") && task.hasA("TimeEnd")) {
            builder.addEventProperty("DTSTART", task.getDate("TimeStart", "YYYYMMDD[T]HHmmss"), false);
            builder.addEventProperty("DTEND", task.getDate("TimeEnd", "YYYYMMDD[T]HHmmss"), false);
          } else {
            builder.addEventProperty("DTSTART", task.getDate(null, "YYYYMMDD"), false);
          }
          this.addEventCommonProperties(task, prependSummary, builder);
          builder.endEvent();
          break;
        case "CreateMultipleEvents":
          if (task.hasA("Start")) {
            builder.beginEvent();
            this.addEventCoreProperties(task, builder);
            builder.addEventProperty("DTSTART", task.getDate("Start", "YYYYMMDD"), false);
            this.addEventCommonProperties(task, "\u{1F6EB} ", builder);
            builder.endEvent();
          }
          if (task.hasA("Scheduled")) {
            builder.beginEvent();
            this.addEventCoreProperties(task, builder);
            builder.addEventProperty("DTSTART", task.getDate("Scheduled", "YYYYMMDD"), false);
            this.addEventCommonProperties(task, "\u23F3 ", builder);
            builder.endEvent();
          }
          if (task.hasA("Due")) {
            builder.beginEvent();
            this.addEventCoreProperties(task, builder);
            builder.addEventProperty("DTSTART", task.getDate("Due", "YYYYMMDD"), false);
            this.addEventCommonProperties(task, "\u{1F4C5} ", builder);
            builder.endEvent();
          }
          if (!task.hasA("Start") && !task.hasA("Scheduled") && !task.hasA("Due")) {
            builder.beginEvent();
            this.addEventCoreProperties(task, builder);
            builder.addEventProperty("DTSTART", task.getDate(null, "YYYYMMDD"), false);
            this.addEventCommonProperties(task, "", builder);
            builder.endEvent();
          }
          break;
        case "PreferDueDate":
        default:
          builder.beginEvent();
          this.addEventCoreProperties(task, builder);
          if (task.hasA("Start") && task.hasA("Due")) {
            builder.addEventProperty("DTSTART", task.getDate("Start", "YYYYMMDDTHHmmss"), false);
            builder.addEventProperty("DTEND", task.getDate("Due", "YYYYMMDDTHHmmss"), false);
          } else if (task.hasA("Due")) {
            builder.addEventProperty("DTSTART", task.getDate("Due", "YYYYMMDD"), false);
          } else if (task.hasA("Start")) {
            builder.addEventProperty("DTSTART", task.getDate("Start", "YYYYMMDD"), false);
          } else if (task.hasA("TimeStart") && task.hasA("TimeEnd")) {
            builder.addEventProperty("DTSTART", task.getDate("TimeStart", "YYYYMMDD[T]HHmmss"), false);
            builder.addEventProperty("DTEND", task.getDate("TimeEnd", "YYYYMMDD[T]HHmmss"), false);
          } else {
            builder.addEventProperty("DTSTART", task.getDate(null, "YYYYMMDD"), false);
          }
          this.addEventCommonProperties(task, prependSummary, builder);
          builder.endEvent();
          break;
      }
    } else {
      builder.beginEvent();
      this.addEventCoreProperties(task, builder);
      builder.addEventProperty("DTSTART", date, false);
      this.addEventCommonProperties(task, prependSummary, builder);
      builder.endEvent();
    }
  }
  addEventCoreProperties(task, builder) {
    builder.addEventProperty("UID", task.getId(), false);
    builder.addEventProperty("DTSTAMP", task.getDate(null, "YYYYMMDDTHHmmss"), false);
  }
  addEventCommonProperties(task, prependSummary, builder) {
    builder.addEventProperty("SUMMARY", prependSummary + task.getSummary());
    const body = task.getBody();
    if (body) {
      builder.addEventProperty("DESCRIPTION", body);
    }
    builder.addEventProperty("LOCATION", task.getLocation());
  }
  addToDosToBuilder(tasks, settings, builder) {
    tasks.forEach((task) => {
      if (settings.isOnlyTasksWithoutDatesAreTodos && task.hasAnyDate()) {
        return;
      }
      builder.beginToDo();
      builder.addEventProperty("UID", task.getId(), false);
      builder.addEventProperty("SUMMARY", task.getSummary());
      if (task.hasAnyDate()) {
        builder.addEventProperty("DTSTAMP", task.getDate(null, "YYYYMMDDTHHmmss"), false);
      }
      const body = task.getBody();
      if (body) {
        builder.addEventProperty("DESCRIPTION", body);
      }
      builder.addEventProperty("LOCATION", task.getLocation());
      if (task.hasA("Due")) {
        builder.addEventProperty("DUE;VALUE=DATE", task.getDate("Due", "YYYYMMDD"), false);
      }
      builder.endToDo();
    });
  }
};

// src/FileClient.ts
var import_obsidian2 = require("obsidian");
var FileClient = class {
  constructor(vault) {
    this.vault = vault;
  }
  async save(calendar) {
    const settings = SettingsManager.settingsManager.settings;
    const fileRelativePath = `${settings.savePath ? settings.savePath + "/" : ""}${settings.saveFileName}${settings.saveFileExtension}`;
    const file = this.vault.getAbstractFileByPath(fileRelativePath);
    if (file instanceof import_obsidian2.TFile) {
      log("File exists: updating");
      await this.vault.modify(file, calendar);
    } else {
      log("File does not exist: creating");
      await this.vault.create(fileRelativePath, calendar);
    }
  }
};

// src/SettingsTab.ts
var import_obsidian3 = require("obsidian");
var SettingsTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "iCal Pro Settings" });
    new import_obsidian3.Setting(containerEl).setName("Target directory").setDesc("The folder where tasks will be scanned. Use '/' for the entire vault.").addText((text) => text.setPlaceholder("e.g., 100_Logs/daily").setValue(this.plugin.settings.rootPath).onChange(async (value) => {
      this.plugin.settings.rootPath = (0, import_obsidian3.normalizePath)(value);
      await this.plugin.saveSettings();
      this.updateUrlDisplay();
    }));
    new import_obsidian3.Setting(containerEl).setName("File name").setDesc("The name of your generated .ics file.").addText((text) => text.setPlaceholder("obsidian").setValue(this.plugin.settings.filename).onChange(async (value) => {
      this.plugin.settings.filename = value;
      await this.plugin.saveSettings();
      this.updateUrlDisplay();
    }));
    containerEl.createEl("h3", { text: "GitHub Sync Configuration" });
    const githubDesc = containerEl.createEl("div", { cls: "setting-item-description" });
    githubDesc.appendText("To sync your calendar online, you need a ");
    githubDesc.createEl("a", {
      text: "GitHub Personal Access Token",
      href: "https://github.com/settings/tokens?type=beta"
    });
    githubDesc.appendText(" (with Gist permissions) and your ");
    githubDesc.createEl("a", {
      text: "Gist ID",
      href: "https://gist.github.com/"
    });
    githubDesc.appendText(".");
    new import_obsidian3.Setting(containerEl).setName("Personal Access Token").addText((text) => text.setPlaceholder("ghp_...").setValue(this.plugin.settings.githubPersonalAccessToken).onChange(async (value) => {
      this.plugin.settings.githubPersonalAccessToken = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Gist ID").addText((text) => text.setPlaceholder("Paste your Gist ID here").setValue(this.plugin.settings.githubGistId).onChange(async (value) => {
      this.plugin.settings.githubGistId = value;
      await this.plugin.saveSettings();
      this.updateUrlDisplay();
    }));
    containerEl.createEl("h3", { text: "Task & Date Rules" });
    new import_obsidian3.Setting(containerEl).setName("Ignore completed tasks").addToggle((toggle) => toggle.setValue(this.plugin.settings.ignoreCompletedTasks).onChange(async (value) => {
      this.plugin.settings.ignoreCompletedTasks = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Processing multiple dates").setDesc("Priority when a task has multiple dates.").addDropdown((dropdown) => dropdown.addOption("PreferDueDate", "Prefer Due Date").addOption("PreferStartDate", "Prefer Start Date").addOption("CreateMultipleEvents", "Create Multiple Events").setValue(this.plugin.settings.howToProcessMultipleDates).onChange(async (value) => {
      this.plugin.settings.howToProcessMultipleDates = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Your Subscription URL" });
    const urlContainer = containerEl.createEl("div", { cls: "ical-url-container" });
    this.renderUrl(urlContainer);
  }
  updateUrlDisplay() {
    const container = this.containerEl.querySelector(".ical-url-container");
    if (container) {
      container.empty();
      this.renderUrl(container);
    }
  }
  renderUrl(container) {
    const gistId = this.plugin.settings.githubGistId;
    const filename = this.plugin.settings.filename || "obsidian";
    if (gistId) {
      const url = `https://gist.githubusercontent.com/raw/${gistId}/${filename}.ics`;
      container.createEl("code", { text: url, cls: "ical-url-text" });
      const copyBtn = container.createEl("button", { text: "Copy URL", cls: "mod-cta" });
      copyBtn.onClickEvent(() => {
        navigator.clipboard.writeText(url);
        copyBtn.setText("Copied!");
        setTimeout(() => copyBtn.setText("Copy URL"), 2e3);
      });
    } else {
      container.createEl("p", {
        text: "Configure your Gist ID above to generate a subscription URL.",
        cls: "setting-item-description"
      });
    }
  }
};

// src/ObsidianIcalPlugin.ts
var ObsidianIcalPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    console.log("Loading Obsidian iCal Plugin Pro");
    await this.loadSettings();
    this.settingsManager = await SettingsManager.createInstance(this);
    this.icalService = new IcalService();
    this.fileClient = new FileClient(this.app.vault);
    this.addRibbonIcon("calendar-with-checkmark", "iCal Pro: Sync Now", async () => {
      new import_obsidian4.Notice("iCal Pro: Starting synchronization...");
      try {
        await this.saveCalendar();
        new import_obsidian4.Notice("iCal Pro: Sync completed successfully!");
      } catch (error) {
        new import_obsidian4.Notice("iCal Pro: Sync failed. Check console for details.");
        console.error(error);
      }
    });
    this.addSettingTab(new SettingsTab(this.app, this));
    if (this.settings.isPeriodicSaveEnabled) {
      this.registerInterval(window.setInterval(() => this.saveCalendar(), this.settings.periodicSaveInterval * 60 * 1e3));
    }
    this.addCommand({
      id: "save-calendar",
      name: "Save calendar",
      callback: () => {
        this.saveCalendar();
      }
    });
  }
  onunload() {
    console.log("Unloading Obsidian iCal Plugin");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async saveCalendar() {
    logger(this.settings.isDebug).log("Saving calendar...");
  }
};

// src/main.ts
var main_default = ObsidianIcalPlugin;
module.exports = __toCommonJS(main_exports);
